name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        #with:
          #source-url: https://nuget.pkg.github.com/<organization>/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

      - name: Build solution and generate NuGet package
        run: |
          cd Src
          dotnet pack -c Debug -p:PackageVersion=0.0.${{github.run_number}} -o out

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./Src/out/*.nupkg --source https://api.nuget.org/v3/index.json -k ${{secrets.NUGETAPIKEY}} --no-symbols true
